// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// 
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB59meyqPAkIXwtrZB47p_3_X-6rLzuGes',
    appId: '1:348572071409:web:e23949793688b2a653c050',
    messagingSenderId: '348572071409',
    projectId: 'competition-app-e4626',
    authDomain: 'competition-app-e4626.firebaseapp.com',
    storageBucket: 'competition-app-e4626.appspot.com',
    measurementId: 'G-6GMD5BV484',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtD-CAC89G8okvLlIkGgDi8pMGtGIZ2Xg',
    appId: '1:348572071409:android:89356c8947c25b5c53c050',
    messagingSenderId: '348572071409',
    projectId: 'competition-app-e4626',
    storageBucket: 'competition-app-e4626.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8KFCzzxvN5s90dXWaheeDvOmPRWbASdM',
    appId: '1:348572071409:ios:34eb464ec392eb1453c050',
    messagingSenderId: '348572071409',
    projectId: 'competition-app-e4626',
    storageBucket: 'competition-app-e4626.appspot.com',
    iosBundleId: 'com.example.competitionApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8KFCzzxvN5s90dXWaheeDvOmPRWbASdM',
    appId: '1:348572071409:ios:34eb464ec392eb1453c050',
    messagingSenderId: '348572071409',
    projectId: 'competition-app-e4626',
    storageBucket: 'competition-app-e4626.appspot.com',
    iosBundleId: 'com.example.competitionApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB59meyqPAkIXwtrZB47p_3_X-6rLzuGes',
    appId: '1:348572071409:web:ec4c900a2e47ca8253c050',
    messagingSenderId: '348572071409',
    projectId: 'competition-app-e4626',
    authDomain: 'competition-app-e4626.firebaseapp.com',
    storageBucket: 'competition-app-e4626.appspot.com',
    measurementId: 'G-R7ZFHNKMHP',
  );
}
